services:
  front_end:
    image: challenge-frontend
    container_name: front_end
    profiles: ["front-only", "all"]
    ports:
      - "80:8080"
    working_dir: /app
    volumes:
      - ../apps/frontEnd:/app
    tty: true
    env_file:
      - .env  # Ajout de l'env_file

  database:
    image: mongo:latest
    container_name: database
    profiles: ["database-only", "back-only", "all"]
    ports:
      - "27017:27017"
    env_file:
      - .env  # Ajout de l'env_file
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db/
      - mongodb_log:/var/log/mongodb/

  back_end:
    image: challenge-backend
    container_name: back_end
    profiles: ["back-only", "all"]
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ../apps/backEnd:/app
    depends_on:
      - database
    tty: true
    env_file:
      - .env  # Ajout de l'env_file

  db_webviewer:
    image: mongo-express:latest
    container_name: db_webviewer
    profiles: ["database-only", "back-only", "all"]
    env_file:
      - .env  # Ajout de l'env_file
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${DB_PORT}
      - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
      - ME_CONFIG_BASICAUTH_USERNAME=${WVDB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${WVDB_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - database

volumes:
  mongodb_data:
    driver: local
    name: mongo_data
  mongodb_log:
    driver: local
    name: mongo_log
