name: test unitaire backEnd
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_USERNAME: esgi
          envkey_DB_PASSWORD: esgi
          directory: /docker
      - name: start only MongoDB
        run: npm run dev:db
      - name: Test
        run: npm run test:unit
